language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

jdk:
  - oraclejdk8

script:
  - ./gradlew build

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: "goa2Y9gpByyz8oP7vSKzzERk5mGCrDK9RcJ0Ev0bCDMy+0rydT0tmnp+Oo99gkgGNJZwW53IffT9xove8Haispp8JSNrn7dTnCgzN2uzwMWzn2wp1S3tlSTYI4el3sbSN2Xa/Fen2ZJdB6T+rbJtI22Ar3hNLSIi5QuxVNl2a8klPxwFGauGYRTvt/HeBa+mSbyHQP104K6itVXFEObTfcmlMdcZ/p5q8Se2WiwwPblSXOE9WhrW3656qL1g13Zhdd9d3kqJw5fBSG29eyvs/7WlyipJoIL+/8rvnC9oE65NMWqveCjRUAwKblislv3wndEmLE2ARHeooa50Z7KOJ/oAqk0l/JPUAJ3/GuDesaiT+4dr+qT4J/DM4ZN71Xk6nFrTbCapbV9ZzEHyqhPNtVs7bDEe61z/5NohUURFn4wwqTI1302h15XJcJORdDEglpNND439v/Zn/xr487qGK4zRQKTOgTtwpAkeYVGHmi7pUj0HE0Lu+bIWzRvIVBvZpm1mFK0BdmmmfuNmamMKwVhel9HfcNk0Pb5+fyvzdhzaegED1V/SM1WApkFENMMGhyWRUZJ/XO3nGFZSQ6S6J5QqL8nLGLo57H4sB56JYb1pBB6e+js8I+aRsAmfxsz7jyf3fOVgzrPdaAhXq5WGCvi7HalFuaiZVwuQ4xQrOLY="
  - secure: "FgjDLAjv01gjN2Q2ZvDkBSPU5Xs7kZnVWeRS5ZZfM/LG5+47CWnZ4Zs04nfqxMwHxQtaO7OXgJi/hGIM3JVof3DalyvZGe13ib9/3UrAJoG9xya66LBpVJYe3gjyhla2RmiMie1VXwNJgtIeuzy+PZaJciVHA+NV2a311AatjOKWufLn/7AGIOeYDQ8swo5cnKLM2E/8zCSD+t8ud9lmx5NhNFOdHkT8DqGyQX5fDbUw6MILzZNI5zJwvfWDnmmGEiNb9Dnr/sGwhe6HSsUmLZbrHT6x59oLcQ8ipggiNnql+6aM7ML6I+Yo+cELRgGTiNmFJiCUTvpxUF4A465QBPwDmbqn76RmQ0wIz2Xq1zjNyjq+Cl69gttGioQdevirfg+Cuvl9QIFPE/uh2Q3BteJWuxNZ+FKFQYaNIkQzubMeaYyD+oXY8jJXQtKHMuzdsPRHMvRchWQRyu+XH69CnQeCbHJdHTXRCpHfCCdg1USo1W+JRR2Bb3jmMeXJLCSERRcAFMGnHZxlw9+gzRdzvOsnmgoWaEkePvoNdZPdG1MJkCKFZEUBfZ5gweTutvWx1DPe0HYUIzP7DzTM2pBFuTWPAvK/dwCtXFudhWY0Dnubky+K6nG0d0wpWfd2Tp+0lwalneM1/CWf64Y9Lgk4IrXxIBrmm2gWVQobtNBb7jA="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
  - $HOME/.gradle